// <auto-generated />
using System;
using BTRS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTRS.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240111154438_BTRS")]
    partial class BTRS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BTRS.Models.administrator", b =>
                {
                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("BTRS.Models.BookingTrips", b =>
                {
                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripID");

                    b.ToTable("bookingtrips");
                });

            modelBuilder.Entity("BTRS.Models.bus", b =>
                {
                    b.Property<int>("BusID")
                        .HasColumnType("int");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int?>("TripID")
                        .HasColumnType("int");

                    b.HasKey("BusID");

                    b.HasIndex("TripID");

                    b.ToTable("bus");
                });

            modelBuilder.Entity("BTRS.Models.passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassengerID");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("BTRS.Models.trip", b =>
                {
                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PassengerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("administratorAdminID")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.HasIndex("PassengerID");

                    b.HasIndex("administratorAdminID");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("BTRS.Models.bus", b =>
                {
                    b.HasOne("BTRS.Models.trip", null)
                        .WithMany("Buses")
                        .HasForeignKey("TripID");
                });

            modelBuilder.Entity("BTRS.Models.trip", b =>
                {
                    b.HasOne("BTRS.Models.passenger", null)
                        .WithMany("Trips")
                        .HasForeignKey("PassengerID");

                    b.HasOne("BTRS.Models.administrator", null)
                        .WithMany("Trips")
                        .HasForeignKey("administratorAdminID");
                });

            modelBuilder.Entity("BTRS.Models.administrator", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BTRS.Models.passenger", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BTRS.Models.trip", b =>
                {
                    b.Navigation("Buses");
                });
#pragma warning restore 612, 618
        }
    }
}
